services:
  pi-home-dash:
    build: .
    volumes:
      - ./temp:/app/temp
      - ./cache:/app/cache
      - ./logs:/var/log
      - ./test_results:/app/test_results
    environment:
      DEBUG: ${DEBUG}
      DAKBOARD_URL: ${DAKBOARD_URL}
      DISPLAY: :99
      PYTHONPATH: /app/src
      UPDATE_INTERVAL: ${UPDATE_INTERVAL}
      DISPLAY_WIDTH: ${DISPLAY_WIDTH}
      DISPLAY_HEIGHT: ${DISPLAY_HEIGHT}
      DASHBOARD_TYPE: ${DASHBOARD_TYPE}
    networks:
      - pi-dash-network

networks:
  pi-dash-network:
    driver: bridge
