services:
  pi-home-dash:
    build: .
    volumes:
      - ./temp:/app/temp
      - ./cache:/app/cache
      - ./logs:/var/log
      - ./test_results:/app/test_results
    environment:
      DEBUG: ${DEBUG:-true}
      DAKBOARD_URL: ${DAKBOARD_URL:-https://dakboard.com/screen/your-screen-id}
      DISPLAY: :99
      PYTHONPATH: /app/src
      UPDATE_INTERVAL: ${UPDATE_INTERVAL:-60}
      FULL_REFRESH_INTERVAL: ${FULL_REFRESH_INTERVAL:-3600}
      DISPLAY_WIDTH: ${DISPLAY_WIDTH:-1872}
      DISPLAY_HEIGHT: ${DISPLAY_HEIGHT:-1404}
      DASHBOARD_TYPE: ${DASHBOARD_TYPE:-dakboard}
    networks:
      - pi-dash-network

networks:
  pi-dash-network:
    driver: bridge
